# This is only used by the indexer
development:
  - http://localhost:8983/solr/core0
test:
  - http://localhost:8983/solr/core0
production: &prod
  - http://mediashelf1.dtic.dk:8080/solr_dtu_search/core0
  - http://mediashelf3.dtic.dk:8080/solr_dtu_search/core0
production2:
  <<: *prod

