#!/usr/bin/env ruby
# encoding: utf-8

require File.join(File.dirname(__FILE__), '../config/environment.rb')
extend ActiveSupport::Benchmarkable

q = Carrot.queue('search.index')


sql = "SELECT id FROM #{Metastore.table_name}"
conn = Metastore.connection
ActiveRecord::Base.transaction do
  conn.execute("declare csr cursor for #{sql}")

  while rows = conn.execute("fetch 10000 from csr").collect {|row| row }
    break if rows.size < 1

    rows.each do |m|
      q.publish(m['id'])
    end
  end
  conn.execute('close csr')
end



Carrot.stop
