#!/usr/bin/env ruby
# encoding: utf-8

require File.join(File.dirname(__FILE__), '../config/environment.rb')
extend ActiveSupport::Benchmarkable

q = Carrot.queue('search.index')


sql = "SELECT id FROM #{Metastore.table_name} limit 1000000"
conn = Metastore.connection
conn.execute("declare csr cursor for #{sql}")

while rows = conn.execute("fetch 20 from csr")
  rows.each do |m|
puts m['id']
#  q.publish(m['id'])
  end
end

conn.execute('close csr')


Carrot.stop
