#!/usr/bin/env ruby
# encoding: utf-8

require File.join(File.dirname(__FILE__), '../config/environment.rb')
extend ActiveSupport::Benchmarkable
if ARGV[0] == '--help'
  puts "Useage: "
  puts "\tenqueue_jobs <starting id> <ending id> <queue name>"
  puts "\tenqueue_jobs <starting id> <ending id>"
  puts "\tenqueue_jobs <number of rows>\n\n"
  puts "\tstarting_id is inclusive, ending id is exclusive"
  puts "\tdefault queue name is search.index\n\n"
  exit
end

if ARGV[1]
  limit_query = " WHERE id >= #{ARGV[0]} AND id < #{ARGV[1]} ORDER BY id"
else
  limit = ARGV[0]
  limit_query = " LIMIT #{limit}" if limit
end

queue_name = ARGV[2] || 'search.index'
 

sql = "SELECT id FROM #{Metastore.table_name}#{limit_query}"

q = Carrot.queue('search.index')
conn = Metastore.connection
ActiveRecord::Base.transaction do
  conn.execute("declare csr cursor for #{sql}")

  while rows = conn.execute("fetch 10000 from csr").collect {|row| row }
    break if rows.size < 1

    rows.each do |m|
      q.publish(m['id'])
    end
  end
  conn.execute('close csr')
end



Carrot.stop
