#!/usr/bin/env ruby
# encoding: utf-8

require File.expand_path(File.join(File.dirname(__FILE__), '../config/environment.rb'))
require 'dtu'

NUM = ARGV[0] || 15

workers = []
threads = []
NUM.to_i.times do |n|
  worker = DTU::QueueWorker.new
  workers << worker
  threads << Thread.new { worker.run }
end

Signal.trap("INT") { workers.each {|w| w.stop} }

threads.each do |thread|
  thread.join
end
