#!/usr/bin/env ruby
# encoding: utf-8

require File.expand_path(File.join(File.dirname(__FILE__), '../config/environment.rb'))
shards = YAML.load_file(Rails.root + 'config/shards.yml')[Rails.env]
threads = []

# if an index is supplied (starting at 0) optimze that shard. Otherwise optimize all of them.
if (ARGV[0])
  puts "Optimizing #{ARGV[0]}"
  solr = RSolr.connect :url => shards[ARGV[0].to_i]
  solr.optimize
else
  shards.each do |shard|
    threads << Thread.new {
      solr = RSolr.connect :url => shard
      solr.optimize
    }
  end

  threads.each do |thread|
    thread.join
  end
end


