#!/usr/bin/env ruby
# encoding: utf-8

require File.expand_path(File.join(File.dirname(__FILE__), '../config/environment.rb'))
shards = YAML.load_file(Rails.root + 'config/shards.yml')[Rails.env]
threads = []
shards.each do |shard|
  threads << Thread.new {
    solr = RSolr.connect :url => shard
    solr.optimize
  }
end

threads.each do |thread|
  thread.join
end


