#!/usr/bin/env ruby
# encoding: utf-8

require File.join(File.dirname(__FILE__), '../config/environment.rb')
extend ActiveSupport::Benchmarkable

require "rubygems"
require "carrot"

q = Carrot.queue('search.index')

Metastore.limit(1).each do |m|
  q.publish(m.id)
end

Carrot.stop
