#!/usr/bin/env ruby
# encoding: utf-8

require File.join(File.dirname(__FILE__), '../config/environment.rb')
require 'buffered_indexer'
require 'journal_encoder'

q = Carrot.queue('search.index')

encoder = JournalEncoder.new
buff = BufferedIndexer.new
    

while msg = q.pop
  list = [msg]
  9.times do
    list << q.pop
  end
  l = Metastore.find(list)
  l.each do |m|
    buff.add(JournalEncoder.solrize(m.xml))
  end
end
buff.flush

Carrot.stop
